const CONFIG = {
    introTitle: 'Bạn Vy ơi!',
    introDesc: `Thôi thì mình bỏ qua vụ đực, cái và chấp nhận bạn Vy vậy, có lỗ là được :3`,
    btnIntro: 'hehe',
    title: 'Mình yêu bạn :3',
    desc: 'bạn có yêu mình hong :3 ',
    btnYes: 'Có =))',
    btnNo: 'hong bé ơi',
    question:'Tại sao bạn lại yêu mình <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'tại yêu thì yêu mà không yêu cũng phải yêu <333333333333',
    mess: 'mình biết mà 🥰. Yêu bạn nhiều😘😘',
    messDesc: 'Mai chơi game với mình tiếp nhé UwU',
    btnAccept: 'Dạaaaaa <3',
    messLink: 'https://www.messenger.com/t/100077651577057' }
