const CONFIG = {
    introTitle: 'Cảm ơn vì đã tin tưởng ấn vào đường link này <3',
    introDesc: `Chào mừng bạn tham gia chương trình bốc thăm may mắn siêu dth này :>>`,
    btnIntro: 'Ucii :>',
    title: 'Nhưng bạn sẽ đánh đổi một thứ khi tham gia chương trình này',
    desc: 'Bạn có muốn tiếp tục không? ',
    btnYes: 'Cóoo',
    btnNo: 'hong :<',
    question:'Vui lòng nhập ngày sinh nhật của bạn để tham gia',
    btnReply: 'Gửi câu trả lời',
    reply: '15-7-2006',
    mess: 'Chúc mừng bạn đã chúng giải! thứ đánh đổi chính là nỗi buồn của bạn nha <3',
    messDesc: 'Like một cái để nhận giải nha :3',
    btnAccept: 'Dạa <3',
    messLink: 'https://www.messenger.com/t/100077651577057' }
